CONFIGURATION = Release
PROJECT       = src\Horstmeier.NugetLicenses\Horstmeier.NugetLicenses.csproj
TEST_PROJECT  = tests\Horstmeier.NugetLicenses.Tests\Horstmeier.NugetLicenses.Tests.csproj

all: build

restore:
	dotnet restore

build: restore
	dotnet build -c $(CONFIGURATION) --no-restore

test: build
	dotnet test -c $(CONFIGURATION) --no-build

test-unit: build
	dotnet test -c $(CONFIGURATION) --no-build --filter "Category!=Integration"

pack: build
	dotnet pack $(PROJECT) -c $(CONFIGURATION) --no-build

install: pack
	dotnet tool install --global --add-source src\Horstmeier.NugetLicenses\bin\$(CONFIGURATION) Horstmeier.NugetLicenses

uninstall:
	dotnet tool uninstall --global Horstmeier.NugetLicenses

clean:
	dotnet clean -c $(CONFIGURATION)
	if exist src\Horstmeier.NugetLicenses\bin rmdir /s /q src\Horstmeier.NugetLicenses\bin
	if exist src\Horstmeier.NugetLicenses\obj rmdir /s /q src\Horstmeier.NugetLicenses\obj
	if exist tests\Horstmeier.NugetLicenses.Tests\bin rmdir /s /q tests\Horstmeier.NugetLicenses.Tests\bin
	if exist tests\Horstmeier.NugetLicenses.Tests\obj rmdir /s /q tests\Horstmeier.NugetLicenses.Tests\obj
